### ISSUE TITLE
Create global state management

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#10]
Create global state management so apps can share information between each other or with other application like a dashboard trough API functions. Also this global state management will be use inside one  map (app) to store state of the map so every component knows what is going on and the state can be share to reinitialize another app with the same state.

Use React Context
https://tyrannosaurustech.com/blog/global-state-management-with-react-hooks-and-context/
https://dev.to/ryanmoragas/global-state-in-react-2kcp

This context needs to used carefully, we do not want all component to be able to modify the state value. Only the creator of that state should be able to modify the state. Other subscriber can consult the value.

### Few use cases
* With this, a map can listen to an extent change from another map and then zoom to that extent.
* A dash board component from another app query the state to know features value from a layer to create a chart
*  State from a map (basemap, extent, loaded layers with display parameter, user annotation, ...) can be share to another app to reproduce the same map

### List of state / events to follows
* [x] Initial configuration
* [x] Loaded basemap and projection
* [x] View extent and zoom Level
* [x] Loaded layer with visibility and opacity setting
* [x] Subscribe to extent change (moveEnd, zoomEnd)
* [x] Open panel and active tool
* [x] Map language

**Comment by yass0016** [comment]
I have been researching about how we can use the Context API to share the same state, it seems it's currently not possible with Context API. I have implemented the state using the Context API but each map will get it's own state and there is no way to consume that state outside of these maps.

After reading for few hours we might use Redux for this. I implemented the state in redux now and we are able to share the same state from both maps in any component. I believe redux is the way to go. Let me know what you think?

**Comment by jolevesq** [comment]
That is good, I was afraid we can't do it without the help of an outside library.

**Comment by yass0016** [comment]
### List of state / events to follows
* [x] Initial configuration
can be accessed wtih `cgpv.api.map(mapId).mapProps`
* [x] Loaded basemap and projection
can be accessed with `cgpv.api.map(mapId).basemap.basemapsList`
* [x] View extent and zoom Level
can be accessed by listening to an event on the map with the event names `map/moveend` for position and `map/zoomend` for zoom
* [x] Loaded layer with visibility and opacity setting
can be accessed with `cgpv.api.map(mapId).layer.layers`
* [x] Subscribe to extent change (moveEnd, zoomEnd)
* [x] Open panel and active tool
* [ ] Map language
