### ISSUE TITLE
[FEATURE] Make sure legend UI works with store and changes are reflected in the map

### ISSUE THREAD

**Issue by cphelefu** [Canadian-Geospatial-Platform/geoview#1526]
This tasks involves doing the following;

- [ ]  Make sure we are showing the right icons each layer.
- [ ] ~Make sure the visibility icons also toggles layers on the map~ part of #1555
- [ ] Make sure the visibility icons also toggles layers on the legend.
- [ ] ~Make sure opacity control propagates to the map too.~ part of #1555
- [ ] ~Removing layers should also propagate to the map and other tabs.~ part of #1555
- [ ] Zoom to layer button (Add tooltip)
- [ ] ~Zoom to layer button should propagate to the map~ part of #1555
- [ ] ~Highlight icon should propagate to the map.~ part of #1555
- [ ] Refresh layers icon should propagate to the UI (while loading) and also the map.
- [ ] ~Table View icon should open the DataTable in a modal **~ part of #1555

BUGS
- [ ] In the legend (We are showing a different download icon)
- [x] Add tooltips to all icons on the top right.
- [x] Images on the right panel should have a max width/height.
