### ISSUE TITLE
Add Datatable

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#218]
Add a datatable plugin to show feature attributes for a layer. it should support the following format:
- [ ] WMS linked table
- [ ] WFS
- [ ] CSV
- [ ] GeoJSON
- [ ] OGC API
- [ ] ESRI dynamic - feature
- ...

The table should have the following functions:
- [ ] Show feature symbol
- [ ] Zoom to feature geometry
- [ ] Filter capability by field and the whole table (contains and start with)
- [ ] Filter spatially the map (if layer type allow it) from attribute
- [ ] Filter the table from map extent and geometry draw on a map
- [ ] Show/hide column
- [ ] Sort column
- [ ] Clear all filters
- [ ] Export result to CSV - GeoJSON
- [ ] Show entries i.e. 1 - 7 of 132 entries shown (filtered from 325 total entries)
- [ ] Datatable may be in a panel inside the viewer or outside
- ...

Issues will be created and added to this epic as needed

Evaluate Material-ui free datatable versus the paid version: 
https://mui.com/api/data-grid/data-grid/
https://mui.com/api/data-grid/data-grid-pro/
 - https://mui.com/x/
 - https://mui.com/components/data-grid/#commercial-version
