### ISSUE TITLE
Add Chart / Dashboard

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#266]
In RAMP we have a plugin to generate a chart on feature click (https://jolevesq.github.io/contributed-plugins/chart/samples/chart-index.html?sample=1). We are using the library ChartJS and NoUiSlider for the slider filter. We will need something similar inside GeoView.

The goal will be to not tie up the chart construction with the feature click but be accessible from outside to just pass configuration and data to generate a chart output to use anywhere.

We will have to support 
- [ ] Pie chart
- [ ] Bar chart
- [ ] Line chart
- [ ] Date, linear log axis
- [ ] Selector for multiple chart
- [ ] Legend selector to add remove items

Material UI has chart and slider component. Make evaluation if we should continue with the libraries we have in RAMP or we switch. **Analysis of D3** for a chart library should be part of the plan.

Maybe having both depending of the task may be a good idea.
- https://www.createwithdata.com/d3js-or-chartjs/

Issues will be created and added to this epic as needed.
