### ISSUE TITLE
Google Earth Engine POC

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#274]
Issues to support the Google Earth Engine proof of concept. To showcase the use of GEE layer inside our current viewer, we will add  1-2 layers from API calls, basic interface for API setting selection, add chart from API results.

- [ ] Data format Landsat, sentinel
- [ ] API call NVDI across the country
- [x] #331
- [ ] Customizable interface from Data selection. Interface should render itself from a JSON configuration (object, schema, ...)
- [ ] Chart capacity from map click call to GEE API

To achieve this we will base out POC on the work done by Climate Engine
- https://docs.climateengine.com/docs/build/html/index.html
- https://app.climateengine.com/climateEngine
- https://explore.etdata.org/#5/39.665/-110.396

Climate Engine team will help by providing some links to the API plus a the API key
