### ISSUE TITLE
Vector Handling - Constant payload for details info and details panel refactor

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#439]
Create a constant payload for how layer gets details information. This payload will be build as interface on super class that layer who needs it may implement it. It will standardize the return value of different ways of getting feature info for layer to remove most of the logic from details panel to layer itself.

This return payload can even be reuse in the table-panel as well.

Layer type using this payload
- WMS (get feature info)
- ESRI dynamic and feature
- Vector, marker
- GeoJSON
- WFS
- OGC Feature API, PyGeoAPI

Tasks
- [x] Create high level payload based on what to expect from details/table point of view
- [x] Create a more near technology payload (payload structure and mapping from different layer)
- [x] Create functions for each layer
- [x] Refactor details-panel

Details-panel will at the end subscribe to layer add event to have is list of layers. On map click, it will loop trough the layers and query the detailsInfo then build from the constant payload the UI.
