### ISSUE TITLE
Add footer bar as internal package

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#499]
- [x] Add styling to the footer tabs component
- [x] Add properties in the schema to enable/disable the footers component just like other components such as north-arrow, overview-map, appbar, navbar
- [x] Add properties in the schema to configure the footer tabs component, maybe allow it to start either expanded, collapsed

It will be a core packages because it needs config

**Comment by jolevesq** [comment]
Relate to #497
