### ISSUE TITLE
Create custom reusable panel

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#6]
Create a custom reusable panel component to be reuse by the other components.

We should have basic panel

* [x] App bar panel
* [x] Modal window
* [x] Customizable size panel (trigger from outside with the api)
* [x] Link panel (the div is pass to the function and the viewer will create the panel from it). It will be outside the viewer div

**Comment by jolevesq** [comment]
I want template for button, panel that can be create from outside. I do it for the layers panel who use the app bar panel. We should have this accessible from outside our app so people can start to build plugin. We should be able to create app bar panel/button, custom panel (size and trigger... can be triger after map click), nav bar button/panel. Can you take a look at this and update the issue?

**Comment by yass0016** [comment]
For buttons you mean allow the user to create a button in the app bar that if clicked will open a custom panel?

**Comment by jolevesq** [comment]
Yes, this is one of the use case. It is how app bar plugin should work (button-panel). From the plugin it should be able to acees the api and the map to do something in his panel. We have the custom panel who can open an any event, the user will open it himself. Then another tool can be added inside the navbar section It can be just a button who does something but it can also be a button-panel pair. In this case, the panel size can be different. The user should be able to modify header (title, add control) and body.

**Comment by yass0016** [comment]
Modal, Panel implemented in core/ui
